- name: Get up a container for the main app
  docker_container:
    name: "myapp"
    image: centos:7
    state: started
    network_mode: host
    exposed_ports: 8000
    command: python -m "SimpleHTTPServer"
